<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Miller.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="Avalonia.Headless.AvaloniaTestApplicationAttribute">
      <_Parameter1>Miller.Tests.TestAppBuilder</_Parameter1>
      <_Parameter1_TypeName>System.Type</_Parameter1_TypeName>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Include="Golden/*.nc" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Miller.Solver/Miller.Solver.csproj" />
    <ProjectReference Include="../../src/Miller.Core/Miller.Core.csproj" />
    <ProjectReference Include="../../src/Miller.Application/Miller.Application.csproj" />
    <ProjectReference Include="../../src/Miller.App/Miller.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
</Project>
