<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Miller.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" Exclude="**/*.placeholder.md" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Miller.Application/Miller.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
</Project>
