<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Miller.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Miller.Core/Miller.Core.csproj" />
    <ProjectReference Include="../Miller.Machine/Miller.Machine.csproj" />
  </ItemGroup>
</Project>
