#!/usr/bin/env bash
# Shared helpers for the PreToolUse guards. Sourced, never executed directly.
# jq-free by design: hooks must run under Git Bash on Windows where jq is absent.
#
# Callers MUST fail closed if this file cannot be sourced - a guard that
# silently degrades to "allow" is worse than no guard.
#
# CONSEQUENCE OF THAT RULE, learned the hard way: while this file does not parse,
# EVERY gated tool is denied - Bash, PowerShell, Edit, Write and Agent alike -
# because each of their guards sources it before reading its own input. There is
# then no route back from inside the session; only the user can repair the file.
# So never edit this file by line offset or by splicing. Write it whole, or
# verify a copy with `bash -n` and only then move it into place.
#
# A SECOND failure mode, found by probing: a guard that ABORTS (unbound variable,
# missing script, killed process) exits non-zero having printed no decision, and
# the runtime treats that as "no opinion" - the call proceeds. Every gate
# therefore installs an EXIT trap that emits a deny on any non-zero exit.

# --- protected assets --------------------------------------------------------
# Two regexes on purpose. They answer different questions and must not be merged:
#
#   PROTECTED_WRITE_REGEX  - "may Edit/Write create or modify this path?"
#     Path-anchored, matched against a single normalized file path. The
#     cloudflared credentials are matched by extension, not by directory, so the
#     tracked cloudflared/.gitkeep placeholder stays editable.
#
#   PROTECTED_DELETE_REGEX - "may a shell command destroy this?"
#     Unanchored, matched against a command-line segment, and a deliberate
#     superset: the cloudflared directory itself is included, because deleting
#     the directory destroys operator-supplied credentials that cannot be
#     regenerated by the agent.
#
# ALL path matching in this file is case-INSENSITIVE (grep -i at every call
# site). The filesystem here is NTFS, which is case-insensitive: a
# case-sensitive guard is bypassed by typing .CLAUDE/state/current_phase or
# .claude/state/task_mode, both of which open the very same file. Probing
# confirmed both slipped through before this change.
PROTECTED_WRITE_REGEX='(\.env$|deployment\.json$|tokens\.json$|/communicates/[^/]*\.txt$|/server_logs/[^/]*\.txt$|/cloudflared/[^/]*\.(pem|json|yml)$|\.git/|payment_notes_archive/|\.db[^/]*$)'
PROTECTED_DELETE_REGEX='(\.env\b|deployment\.json|tokens\.json|communicates|server_logs|cloudflared|\.git[/\\]|payment_notes_archive|\.db\b)'

# Recursive deletion is permitted only for regenerable build output. Without
# this allowlist the guard blocks `rm -rf build`, which is the fastest route to
# someone disabling the guard entirely.
EPHEMERAL_TARGET_REGEX='^\.?[/\\]?([^[:space:]]*[/\\])?(build|bin|obj|out|dist)[/\\]?$'

# The session scratchpad, and ONLY the scratchpad. This used to also match bare
# AppData/Local/Temp, which exempted every temp file on the machine from the
# read-only phase gate. The `claude` segment is what makes it a scratchpad path.
SCRATCHPAD_TARGET_REGEX='[/\\]temp[/\\]claude[/\\]'

# --- state files the agent may never write -----------------------------------
# The phase state machine is only real if the agent cannot set its own position
# in it. current_phase and task_class are writable exclusively by advance.sh /
# rollback.sh / session-start.sh, which run as hook scripts and are therefore not
# themselves subject to the tool guards. TASK_MODE is the master switch: an agent
# that can delete it can switch every phase rule off.
#
# research_files.done / research_web.done are the join flags of the phase-2
# research block (written by advance.sh only), and agents/ is the sub-agent
# ledger (slot reservations, budgets and agent links, written by the spawn gate
# and the tracking hooks only). An agent that could delete a slot file would
# lift the concurrency limit on itself, so the whole directory is locked.
#
# phase_model is omitted: it is a migration stamp, and a wrong value there only
# ever forces a reset to the start of the process.
AGENT_LOCKED_STATE_REGEX='(^|/)\.claude/state/(current_phase|task_class|TASK_MODE|hook_edit_grant|research_files\.done|research_web\.done|agents(/[^/]*)?)$'

# --- consent to modify the enforcement layer ---------------------------------
# The agent and the hooks share a uid, so no file permission can stop the agent
# rewriting its own guards. What CAN be enforced is a token the agent is unable
# to mint: hook_edit_grant is in the locked-state list above, so Edit, Write and
# the shell are all refused on it at every phase. Only inject-phases.sh writes
# it, and only when the user's prompt contains the passphrase below.
#
# Substring match, by explicit owner decision, so the phrase can be written
# inline with the request it authorises. The trade-off accepted with it: any
# prompt containing the phrase grants, a pasted log included. Two rules follow.
# The guards never print the phrase in a deny reason, so pasting a hook error
# back into chat cannot grant. And the agent does not quote the phrase on its
# own initiative - it points at README.md instead - but does quote it when the
# user asks for it.
#
# The grant lasts one turn. gate-stop.sh deletes it on the path where the turn
# is actually allowed to end, so "until Claude stops thinking" is literal: if the
# Stop gate blocks and work continues, the grant survives; once the turn ends it
# is gone and must be asked for again.
HOOK_EDIT_GRANT_PASSPHRASE="yes claude allowed to modify claude settings"
HOOK_EDIT_GRANT_QUESTION="if AI allowed to modify claude settings?"

hook_edit_grant_active() {
  [[ -f "${1}/hook_edit_grant" ]]
}

hook_edit_grant_revoke() {
  rm -f "${1}/hook_edit_grant" 2>/dev/null
}

# The enforcement layer itself: the wiring config and every hook script. Writing
# these is how an agent switches the guards off, so they are routed to an
# explicit user approval (Edit/Write) or refused outright (shell), instead of
# being silently writable merely because they live under .claude/.
#
# This is a chokepoint, not a proof. The agent and the hooks share a uid, so
# nothing at this layer can be absolute; what it removes is the SILENT path,
# which is the failure mode that actually occurs.
HOOK_INFRA_REGEX='(^|/)\.claude/(settings(\.local)?\.json$|hooks/)'

# --- phase model -------------------------------------------------------------
# Single source of truth for the process defined in the root CLAUDE.md.
# Phases 1-8 are that document's phases, in order. Phase 9 is not a
# development phase: it is the terminal resting state that lets the Stop gate
# distinguish "reporting still owed" from "task finished", and it is the only
# phase the user controls directly.
#
# Phases 2 and 3 of the document run CONCURRENTLY as one block (owner decision,
# 2026-09-17). The block carries the number 2; the number 3 is retired and is
# never produced by advance.sh. Each half is marked finished separately
# (advance.sh "files" / advance.sh "web") and the block joins into phase 4 only
# when both marks are present.
#
#   1 Task definition     read only   KPI table: tasks + acceptance criteria
#   2 Research block      read only   files pre-research + WEB research, at the
#                                     same time; skipped when trivial; leaves
#                                     only when both halves are marked
#   3 (retired number)                never a current phase in this model
#   4 Planning            read only   skipped when trivial; may end the turn
#   5 Execution           free
#   6 Testing             free        may end the turn; rolls back to 1
#   7 Documentation       free        folder-level CLAUDE.md only
#   8 Reporting           read only   shell blocked as well
#   9 Done                free        terminal, user-controlled
PHASE_MIN=1
PHASE_DONE=9
RESEARCH_PHASE=2

# Bumped whenever the meaning of a phase NUMBER changes. A number on its own is
# ambiguous across models - 7 was "Execution" under the retired 11-phase model
# and is "Documentation" here; 3 was "WEB research" under model 2 and is not a
# phase under model 3 - and current_phase survives resume, compact and
# hand-editing. session-start.sh refuses to PRESERVE a phase stamped with an
# older model, and advance.sh normalises it back to PHASE_MIN rather than acting
# on a number it cannot interpret.
PHASE_MODEL_VERSION=3

# The skip rule carried by CLAUDE.md phases 2, 3 and 4: "skip for trivial tasks
# like PR creation". Two values, spelled exactly; the skip table below is keyed
# off them so that skipping is a property of the state machine and never a
# decision the agent makes mid-task.
CLASS_TRIVIAL="trivial"
CLASS_STANDARD="standard"

# The two halves of the research block, spelled exactly. They are the only
# arguments advance.sh accepts at phase 2, the names of the join flags
# (research_<half>.done) and the tags a sub-agent spawned during the block must
# carry in its description ("files: ..." / "web: ...").
RESEARCH_HALF_FILES="files"
RESEARCH_HALF_WEB="web"

phase_name() {
  case "$1" in
    1) printf 'Task definition' ;;
    2) printf 'Research block: files pre-research + WEB research (concurrent)' ;;
    3) printf 'retired number - WEB research is half of phase 2' ;;
    4) printf 'Planning' ;;
    5) printf 'Execution' ;;
    6) printf 'Testing' ;;
    7) printf 'Documentation' ;;
    8) printf 'Reporting' ;;
    9) printf 'Done / post-execution (user-controlled)' ;;
    *) printf 'unknown' ;;
  esac
}

# Exact, case-sensitive match against the two permitted class strings. Any
# paraphrase ("Trivial", "trivial task", "full") is rejected: the whole point of
# fixing the strings is that the skip table can be keyed off them without
# interpretation.
class_is_valid() {
  case "$1" in
    "$CLASS_TRIVIAL"|"$CLASS_STANDARD") return 0 ;;
  esac
  return 1
}

research_half_is_valid() {
  case "$1" in
    "$RESEARCH_HALF_FILES"|"$RESEARCH_HALF_WEB") return 0 ;;
  esac
  return 1
}

# The skip table. CLAUDE.md marks phases 2 (files pre-research), 3 (WEB research)
# and 4 (planning) "skip for trivial tasks like PR creation" - all three carry
# the identical condition, so the trivial class skips the block as a whole.
# Expressed as forward transitions so that skipping is applied by the machine.
#
# 2 -> 4 is the join of the research block. advance.sh takes it only when both
# halves are marked (research_both_done); the number 3 has no transition.
phase_next() {
  local cur="$1" class="${2:-}"
  case "$cur" in
    1)
      case "$class" in
        "$CLASS_TRIVIAL")  printf 5 ;;
        "$CLASS_STANDARD") printf 2 ;;
        *) return 1 ;;
      esac
      ;;
    2) printf 4 ;;
    4) printf 5 ;;
    5) printf 6 ;;
    6) printf 7 ;;
    7) printf 8 ;;
    8) printf 9 ;;
    *) return 1 ;;
  esac
  return 0
}

# Reachability is checked independently of phase_next so that a hand-edited
# current_phase cannot smuggle the agent into a phase its class forbids. The
# retired number 3 is reachable for no class at all.
phase_reachable() {
  local phase="$1" class="${2:-}"
  case "$phase" in
    1) return 0 ;;
    2|4) [[ "$class" == "$CLASS_STANDARD" ]] && return 0 ;;
    5|6|7|8|9) class_is_valid "$class" && return 0 ;;
  esac
  return 1
}

# Read-only phases: 1-4 are the definition, research and planning phases, 8 is
# report-only. Edits outside .claude/ are blocked here, from Edit/Write AND from
# the shell. 3 stays listed: a hand-edited 3 must not become a free phase.
phase_is_readonly() {
  case "$1" in
    1|2|3|4|8) return 0 ;;
  esac
  return 1
}

# Phases whose CLAUDE.md text explicitly involves asking the user something:
# 4 ("Asking questions allowed only in case of missing blocking information")
# and 6 ("ask for test modification approval"). Everywhere else the turn must
# run to completion.
phase_allows_optional_stop() {
  case "$1" in
    4|6) return 0 ;;
  esac
  return 1
}

# --- research block join flags -----------------------------------------------
# One existence flag per half, written by advance.sh only, locked against the
# agent (AGENT_LOCKED_STATE_REGEX). Two files rather than one so that the two
# marks never share a write target and need no lock; a repeated mark is refused
# by advance.sh, so the flag is 1-bounded and the join is order independent.
# The join requires CONTENT (-s), not mere existence: an empty file created by
# hand is not a mark.
research_flag_path() {
  printf '%s/research_%s.done' "$1" "$2"
}

research_half_done() {
  [[ -s "$(research_flag_path "$1" "$2")" ]]
}

research_both_done() {
  research_half_done "$1" "$RESEARCH_HALF_FILES" && research_half_done "$1" "$RESEARCH_HALF_WEB"
}

research_flags_clear() {
  rm -f "$(research_flag_path "$1" "$RESEARCH_HALF_FILES")" "$(research_flag_path "$1" "$RESEARCH_HALF_WEB")" 2>/dev/null
  return 0
}

# --- subagent policy ---------------------------------------------------------
# Root CLAUDE.md: "only opus sub-agents are allowed"; the model is the first
# thing gate-subagent.sh checks. Two limits sit on top of it (owner decision,
# 2026-09-17):
#
#   SUBAGENT_MAX_CONCURRENT  - at most this many sub-agents running at the same
#                              time, at every phase, task mode or not.
#   RESEARCH_FILES_MAX /     - during the phase-2 research block (task mode
#   RESEARCH_WEB_MAX           only) every spawn must carry the half it works
#                              for as a description prefix ("files: ..." or
#                              "web: ..."), and each half has a spawn budget for
#                              the whole block: 5 for files pre-research, 3 for
#                              WEB research (CLAUDE.md phase 3: "max quantity of
#                              agents for this phase is 3").
#
# A running sub-agent still never blocks advance.sh, rollback.sh or the end of a
# turn. Declared once and interpolated into every deny message, because the
# allowlist retyped in several places is exactly how it drifted before.
SUBAGENT_ALLOWED_MODEL="opus"
SUBAGENT_MAX_CONCURRENT=8
RESEARCH_FILES_MAX=5
RESEARCH_WEB_MAX=3

# A reservation that was never linked to a running agent (the spawn was refused
# by the runtime, errored, or its PostToolUse hook never ran) is reclaimed after
# this many minutes. Linked slots never expire by age: a sub-agent may run for
# an hour, and over-admitting is the wrong direction to fail in.
LEDGER_RESERVATION_TTL_MIN=5

# --- subagent ledger ---------------------------------------------------------
# Directory .claude/state/agents/, flat, one file per fact:
#
#   slot.<k>          k = 1..SUBAGENT_MAX_CONCURRENT. Exists while a sub-agent
#                     holds slot k. Created by gate-subagent.sh with an
#                     EXCLUSIVE create (bash noclobber -> O_EXCL), which is the
#                     one primitive verified atomic on both NTFS/Cygwin and
#                     Linux; a burst of parallel spawns therefore admits exactly
#                     SUBAGENT_MAX_CONCURRENT and denies the rest. Content:
#                     reservation id, UTC time, research half or '-'.
#   res.<tool_use_id> Reservation index: which slot the PreToolUse call took.
#   agent.<agent_id>  Link written by track-agent-result.sh from the Agent
#                     tool's response (agentId): line 1 the slot, line 2 the
#                     reservation id. SubagentStop releases through it.
#   budget.<half>.<n> One per admitted research spawn, n = 1..max for the half.
#                     Same exclusive create. Cleared with the block.
#
# Release renames the slot to a private temp name and then deletes it, so the
# slot name is free immediately even where a delete-pending name lingers.
# Nothing here waits: a PreToolUse hook that stalls is not a gate (a timed-out
# hook lets the call through), so a full pool is denied at once.
LEDGER_DIRNAME="agents"

ledger_dir() {
  printf '%s/%s' "$1" "$LEDGER_DIRNAME"
}

utc_now() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Exclusive create: 0 = this call created the file, 1 = it already existed.
# printf, not ':' - a failed redirection on the special builtin ':' terminates
# a POSIX-mode shell. noclobber is toggled only around the attempt.
create_excl() {
  local had_c=0 rc
  [[ $- == *C* ]] && had_c=1
  set -C
  { printf '%s\n' "$2" > "$1"; } 2>/dev/null
  rc=$?
  (( had_c )) || set +C
  return $rc
}

slot_count() {
  local f c=0
  for f in "$1"/slot.*; do
    [[ -f "$f" ]] && c=$((c + 1))
  done
  printf '%s' "$c"
}

# Takes the first free slot. Prints the slot name and returns 0; returns 1 when
# every slot is held; 2 when the ledger directory cannot be created.
slot_acquire() {
  local dir="$1" rid="$2" tag="${3:--}" k
  mkdir -p "$dir" 2>/dev/null || return 2
  for (( k = 1; k <= SUBAGENT_MAX_CONCURRENT; k++ )); do
    if create_excl "$dir/slot.$k" "$rid $(utc_now) $tag"; then
      printf 'slot.%s\n' "$k" > "$dir/res.$rid"
      printf 'slot.%s' "$k"
      return 0
    fi
  done
  return 1
}

slot_free() {
  local dir="$1" slot="$2" tmp
  [[ -n "$slot" && -f "$dir/$slot" ]] || return 1
  tmp="$dir/.rel.$$.$slot"
  mv -f "$dir/$slot" "$tmp" 2>/dev/null || return 1
  rm -f "$tmp" 2>/dev/null
  return 0
}

# The spawn produced no running agent (denied after the reservation, refused by
# the runtime, or finished before the tool call returned): give the slot back.
ledger_release_reservation() {
  local dir="$1" rid="$2" slot
  slot=$(head -n 1 "$dir/res.$rid" 2>/dev/null)
  rm -f "$dir/res.$rid" 2>/dev/null
  [[ -n "$slot" ]] && slot_free "$dir" "$slot"
  return 0
}

# Binds a reservation to the agent id the Agent tool reported. 1 = unknown
# reservation (nothing to bind).
ledger_link_agent() {
  local dir="$1" rid="$2" aid="$3" slot
  slot=$(head -n 1 "$dir/res.$rid" 2>/dev/null)
  [[ -n "$slot" ]] || return 1
  printf '%s\n%s\n' "$slot" "$rid" > "$dir/agent.$aid"
}

# Releases the slot held by a finished agent. 1 = the agent was never linked
# (a spawn from a surface the gate does not see, or a resumed run).
ledger_release_agent() {
  local dir="$1" aid="$2" slot rid
  [[ -f "$dir/agent.$aid" ]] || return 1
  slot=$(sed -n 1p "$dir/agent.$aid" 2>/dev/null)
  rid=$(sed -n 2p "$dir/agent.$aid" 2>/dev/null)
  rm -f "$dir/agent.$aid" 2>/dev/null
  [[ -n "$rid" ]] && rm -f "$dir/res.$rid" 2>/dev/null
  slot_free "$dir" "$slot"
  return 0
}

# Reclaims reservations older than LEDGER_RESERVATION_TTL_MIN that no agent
# link names. Run by the spawn gate before it counts.
ledger_reap() {
  local dir="$1" f slot rid
  [[ -d "$dir" ]] || return 0
  for f in "$dir"/res.*; do
    [[ -f "$f" ]] || continue
    [[ -n "$(find "$f" -mmin +"$LEDGER_RESERVATION_TTL_MIN" 2>/dev/null)" ]] || continue
    slot=$(head -n 1 "$f" 2>/dev/null)
    if ! grep -qsx "$slot" "$dir"/agent.* 2>/dev/null; then
      rid=${f##*/res.}
      ledger_release_reservation "$dir" "$rid"
    fi
  done
  return 0
}

research_half_max() {
  case "$1" in
    "$RESEARCH_HALF_FILES") printf '%s' "$RESEARCH_FILES_MAX" ;;
    "$RESEARCH_HALF_WEB")   printf '%s' "$RESEARCH_WEB_MAX" ;;
    *) printf 0 ;;
  esac
}

budget_count() {
  local f c=0
  for f in "$1"/budget."$2".*; do
    [[ -f "$f" ]] && c=$((c + 1))
  done
  printf '%s' "$c"
}

# Takes the next budget unit of a half. 0 = taken, 1 = budget exhausted,
# 2 = ledger directory unavailable.
budget_acquire() {
  local dir="$1" half="$2" rid="$3" n max
  max=$(research_half_max "$half")
  mkdir -p "$dir" 2>/dev/null || return 2
  for (( n = 1; n <= max; n++ )); do
    create_excl "$dir/budget.$half.$n" "$rid $(utc_now)" && return 0
  done
  return 1
}

budget_clear() {
  rm -f "$1"/budget.* 2>/dev/null
  return 0
}

# Whole-ledger reset, for a process restart: every sub-agent of the previous
# process is gone, so every slot it held is stale.
ledger_clear() {
  rm -rf "$1" 2>/dev/null
  return 0
}

# Bounded audit trail of the spawn/link/stop events, next to the ledger but not
# inside it, so a ledger reset keeps the history that explains it.
subagent_event_log() {
  local state_dir="$1" message="$2" log="${1}/subagent_events.log"
  printf '%s %s\n' "$(utc_now)" "$message" >> "$log" 2>/dev/null
  if [[ -f "$log" ]]; then
    tail -n 200 "$log" > "${log}.tmp" 2>/dev/null && mv -f "${log}.tmp" "$log" 2>/dev/null
  fi
  return 0
}

# --- path normalization ------------------------------------------------------
# Collapses separators and resolves "." and ".." segments TEXTUALLY, so that
# Server/../CLAUDE.md and .claude/state/../state/TASK_MODE cannot slip past
# patterns anchored on the canonical spelling. Probing confirmed both did.
#
# Textual and not realpath on purpose: the target of a Write frequently does not
# exist yet, and realpath returns nothing for a missing path. This closes path
# traversal only. Symlinks, hardlinks and 8.3 short names remain out of reach for
# any string-matching guard - see the README for what this layer does not cover.
normalize_path() {
  printf '%s' "${1//\\//}" | awk '
  {
    lead = ($0 ~ /^\//) ? 1 : 0;
    n = split($0, part, "/");
    top = 0;
    for (i = 1; i <= n; i++) {
      p = part[i];
      if (p == "" || p == ".") continue;
      if (p == ".." && top > 0 && out[top] != "..") { top--; continue }
      out[++top] = p;
    }
    s = "";
    for (i = 1; i <= top; i++) s = s (i > 1 ? "/" : "") out[i];
    if (lead) s = "/" s;
    print s;
  }'
}

# Strips one layer of surrounding quotes, then normalizes. Every guard passes a
# candidate path through this before matching it against anything.
clean_path() {
  local raw="$1"
  raw="${raw%\"}"; raw="${raw#\"}"
  raw="${raw%\'}"; raw="${raw#\'}"
  normalize_path "$raw"
}

# --- fail-closed exit trap ---------------------------------------------------
# Install in every PreToolUse gate as the FIRST statement after `set`:
#   trap 'fail_closed_trap $?' EXIT
# A gate that aborts - unbound variable, missing file, killed process - exits
# non-zero having printed nothing, and the runtime reads that as "no opinion"
# and runs the tool. Probing confirmed all four gates behaved that way when
# CLAUDE_PROJECT_DIR was unset. Emitting a deny on any non-zero exit turns every
# such abort into a refusal.
#
# Defined without depending on anything else in this file, and duplicated inline
# in each gate, because the library itself may be the thing that failed to load.
fail_closed_trap() {
  [[ "${1:-0}" -eq 0 ]] && return 0
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Guard aborted before reaching a decision (exit %s). Failing closed. Check .claude/hooks and CLAUDE_PROJECT_DIR."}}\n' "$1"
}

# --- root CLAUDE.md ----------------------------------------------------------
# The root project CLAUDE.md is user-owned ("project Claude.md in root and
# .claude might be updated only by user"). Folder-level CLAUDE.md files stay
# editable, so the test is "no directory segment in front of it", plus the
# absolute form under the project directory.
is_root_claude_md() {
  local norm project lower_norm lower_proj
  norm=$(clean_path "$1")
  project="${2:-${CLAUDE_PROJECT_DIR:-}}"
  project=$(normalize_path "$project")
  project="${project%/}"
  lower_norm=$(printf '%s' "$norm" | tr '[:upper:]' '[:lower:]')
  lower_proj=$(printf '%s' "$project" | tr '[:upper:]' '[:lower:]')
  [[ -n "$lower_proj" && "$lower_norm" == "${lower_proj}/claude.md" ]] && return 0
  [[ "$lower_norm" == "claude.md" ]] && return 0
  return 1
}

# --- write detection in shell commands ---------------------------------------
# Used by the read-only-phase gate and the root-CLAUDE.md gate. The boundary is
# "not part of a word", NOT whitespace - a quote or paren sits directly before
# the command in `bash -c 'cp a b'`.
CMD_START='(^|[^A-Za-z0-9_.-])'
MUTATION_VERB_REGEX="${CMD_START}(cp|copy|mv|move|install|touch|mkdir|dd|tee|patch|ln|truncate|chmod|chown|set-content|add-content|out-file|new-item|copy-item|move-item|rename-item|remove-item|clear-content|rm|del|erase|unlink|shred|rmdir|rd)([[:space:]]|$)"
INPLACE_EDIT_REGEX="${CMD_START}(sed|perl)([[:space:]]+-[^[:space:]]+)*[[:space:]]+-[a-z]*i"
GIT_WRITE_REGEX="${CMD_START}git([[:space:]]+-[^[:space:]]+)*[[:space:]]+(add|commit|apply|am|checkout|restore|switch|stash|rm|mv|clean|reset|merge|rebase|push|pull|fetch|tag|branch|init|worktree|cherry-pick|revert|update-index|config)([[:space:]]|$)"

# Interpreters that execute inline code handed to them as an argument. A
# redirect inside such an argument is a real write, but redirect_targets treats
# quoted spans as data and skips them - correct for `grep 'a > b'`, wrong for
# `bash -c "echo x > f"`. Probing confirmed the latter escaped the read-only
# gate. write_targets re-scans these segments with quote characters removed.
#
# env/sudo/xargs are absent: they wrap another command that is itself matched
# here (`sudo bash -c ...` still matches bash), and including them would make
# `sudo cat "a > b"` a false positive.
INLINE_INTERPRETER_REGEX="${CMD_START}(bash|sh|zsh|dash|ksh|pwsh|powershell|cmd|python|python3|perl|ruby|node)([[:space:]]|$)"

# Redirection targets, minus the sinks that write nothing real.
#
# Quote-aware by necessity. Two earlier designs both failed:
#   - stripping quoted spans first hid `echo x > "CLAUDE.md"` entirely;
#   - removing quote characters first turned DATA containing '>' into a
#     redirect, so `printf '<task-id>x</task-id>'` was read as a write to
#     `x</task-id>` and blocked in a read-only phase.
# Walking the string with quote state is the only version that gets both right:
# a '>' inside quotes is data, a '>' outside quotes is a redirect, and the
# target that follows is unquoted before being returned.
redirect_targets() {
  printf '%s' "$1" | awk '
  {
    n = length($0); i = 1;
    while (i <= n) {
      c = substr($0, i, 1);
      if (c == "\\") { i += 2; continue }
      if (c == "\047") { i++; while (i <= n && substr($0, i, 1) != "\047") i++; i++; continue }
      if (c == "\"")   { i++; while (i <= n && substr($0, i, 1) != "\"")   i++; i++; continue }
      if (c == ">") {
        i++;
        if (substr($0, i, 1) == ">") i++;
        while (i <= n && substr($0, i, 1) == " ") i++;
        t = "";
        while (i <= n) {
          c2 = substr($0, i, 1);
          if (c2 == " " || c2 == ";" || c2 == "|" || c2 == "&" || c2 == ")") break;
          if (c2 == "\047") { i++; while (i <= n && substr($0, i, 1) != "\047") { t = t substr($0, i, 1); i++ } i++; continue }
          if (c2 == "\"")   { i++; while (i <= n && substr($0, i, 1) != "\"")   { t = t substr($0, i, 1); i++ } i++; continue }
          t = t c2; i++;
        }
        if (t != "") print t;
        continue;
      }
      i++;
    }
  }' | grep -vE '^(/dev/null|\$null|nul|NUL|&[0-9])$'
}

# Every non-flag argument of a segment, first token excluded.
command_targets() {
  printf '%s' "$1" | tr -s '[:space:]' '\n' | grep -v '^$' | tail -n +2 \
    | grep -vE '^-' | grep -vE '^/[a-zA-Z]$' | grep -vE '^>'
}

# Paths the agent may still write while a read-only phase is in force: its own
# state area and the session scratchpad. AGENT_LOCKED_STATE_REGEX and
# HOOK_INFRA_REGEX are enforced separately and outrank this.
is_agent_writable_target() {
  local t
  t=$(clean_path "$1")
  printf '%s' "$t" | grep -qiE '(^|/)\.claude/' && return 0
  printf '%s' "$t" | grep -qiE "$SCRATCHPAD_TARGET_REGEX" && return 0
  return 1
}

# --- hook I/O ----------------------------------------------------------------
# Extract a JSON string field. Greedy by nature, which is safe here: JSON escapes
# every quote inside a value, so a decoy "field":"..." embedded in payload data
# cannot present the unescaped '":"' this pattern requires.
hook_json_string() {
  local input="$1" field="$2"
  printf '%s' "$input" | sed -nE 's/.*"'"$field"'"[[:space:]]*:[[:space:]]*"(([^"\\]|\\.)*)".*/\1/p'
}

json_unescape() {
  local s="$1"
  s="${s//\\\\/\\}"
  s="${s//\\\"/\"}"
  s="${s//\\n/$'\n'}"
  printf '%s' "$s"
}

json_escape() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}
  printf '%s' "$s"
}

# Emits a PreToolUse deny and terminates the calling hook.
deny_pretooluse() {
  local reason="$1"
  echo "BLOCKED: $reason" >&2
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' \
    "$(json_escape "$reason")"
  exit 0
}

# Emits a PreToolUse ask - an explicit user button press. An ask outranks
# defaultMode=bypassPermissions, which is what makes it usable as an approval
# gate rather than a suggestion.
ask_pretooluse() {
  local reason="$1"
  echo "ASK: $reason" >&2
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":"%s"}}\n' \
    "$(json_escape "$reason")"
  exit 0
}

# --- phase state readers -----------------------------------------------------
read_phase() {
  local state_dir="$1" phase
  phase=$(cat "${state_dir}/current_phase" 2>/dev/null || echo "$PHASE_MIN")
  [[ "$phase" =~ ^[0-9]+$ ]] || phase="$PHASE_MIN"
  # Clamp instead of trusting the number. A value left behind by the retired
  # 11-phase model (10 = Reporting, 11 = Done) would otherwise name a phase that
  # no longer exists. Clamping to the terminal phase is the safe direction: the
  # Stop gate lets the turn end and session-start.sh resets the state, rather
  # than a task running under a phase number nobody defines.
  (( phase < PHASE_MIN )) && phase="$PHASE_MIN"
  (( phase > PHASE_DONE )) && phase="$PHASE_DONE"
  printf '%s' "$phase"
}

read_task_class() {
  local state_dir="$1"
  cat "${state_dir}/task_class" 2>/dev/null || printf ''
}

# --- phase model version -----------------------------------------------------
# The version stamp is what makes a renumbering safe. Without it a persisted
# phase number from an older model is indistinguishable from a current one.
phase_model_recorded() {
  cat "${1}/phase_model" 2>/dev/null || printf ''
}

phase_model_is_current() {
  [[ "$(phase_model_recorded "$1")" == "$PHASE_MODEL_VERSION" ]]
}

phase_model_stamp() {
  printf '%s' "$PHASE_MODEL_VERSION" > "${1}/phase_model"
}

# Append a loud, timestamped entry that gate-stop.sh surfaces. Silent hook
# failures were the actual defect: a failed state update used to exit 0 with no
# trace.
hook_error() {
  local state_dir="$1" message="$2"
  printf '%s %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$message" >> "${state_dir}/hook_errors.log"
  echo "HOOK ERROR: $message" >&2
}
